services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: 'npm'
      DB_MYSQL_NAME: 'npm'
      DISABLE_IPV6: 'true'
    volumes:
      - /mnt/docker-data/services/npm/data:/data
      - /mnt/docker-data/services/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - /mnt/docker-data/services/npm/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pnpm"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 60s

networks:
  default:
    name: services_network
    external: true
