services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      DB_MYSQL_HOST: '127.0.0.1'
      DB_MYSQL_PORT: 3307
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: 'npm'
      DB_MYSQL_NAME: 'npm'
      DISABLE_IPV6: 'true'
    volumes:
      - /mnt/docker-data/services/npm/data:/data
      - /mnt/docker-data/services/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    ports:
      - '127.0.0.1:3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - /mnt/docker-data/services/npm/db:/var/lib/mysql
