services:
  emby:
    image: emby/embyserver:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - /mnt/docker-data/services/emby/config:/config
      - /mnt/docker-data/services/emby/media:/media
      - /mnt/docker-data/services/emby/dad-media:/dad-media

networks:
  default:
    name: services_network
    external: true
